### PR TITLE
sinatra.route is required for an action name

### LINKED ISSUE #143: Sinatra requests to endpoints to that aren't defined in sinatra crash the transaction
Apparently something goes wrong when a request is send to something like "/phpmyadmin" and a sinatra app doesn't listen to that endpoint. Then the appsignal gem tries to find that endpoint, but can't and crashes.

The server registers these multiple requests as 1 very long request. The transaction eventually closes when a successful requests finally happen, and the transaction actually completes.

```
undefined method `split' for nil:NilClass
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/appsignal-1.3.2/lib/appsignal/rack/sinatra_instrumentation.rb:80:in `action_name'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/appsignal-1.3.2/lib/appsignal/rack/sinatra_instrumentation.rb:67:in `ensure in call_with_appsignal_monitoring'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/appsignal-1.3.2/lib/appsignal/rack/sinatra_instrumentation.rb:71:in `call_with_appsignal_monitoring'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/appsignal-1.3.2/lib/appsignal/rack/sinatra_instrumentation.rb:37:in `call'
```

Reported in: https://app.intercom.io/a/apps/yzor8gyw/inbox/conversation/5598150053

### PR DESCRIPTION
**Pull request by tombruijn**
Fixes #143

Apparently something goes wrong when a request is send to something like
"/phpmyadmin" and a Sinatra app doesn't listen to that endpoint. Then
the appsignal gem tries to find that endpoint, but can't and crashes the
current transaction.

Most commonly triggered by defining an optional route and then
triggering a request to a page on that route (or even outside that
route) which doesn't exist.

The Sinatra server will then continue to register new requests under
this crashed transaction, but also create new ones. The new requests
will be seen as part of one very long request, because the original
crashed transaction remains open.

This continues until eventually a successful requests finally happens
and the transaction closes, then the original transaction actually
completes.

Problem is that now many more transactions can have started during this
crashed transaction nesting other transactions within one another.
Visually this creates a transaction that could have been open for X
amount of time and has request data from multiple requests merged
together.

### CODE REVIEW

File: spec/lib/appsignal/rack/sinatra_instrumentation_spec.rb [hunk 1]
```diff
@@ -131,12 +131,28 @@
...
             Appsignal::Transaction.any_instance.should_receive(:set_action).with("GET /api/v2/")
           end
+
+          context "without 'sinatra.route' env" do
+            let(:env) { {:path => '/', :method => 'GET'} }
+
+            it "returns nil" do
+              Appsignal::Transaction.any_instance.should_receive(:set_action).with(nil)
+            end
+          end
```
Comment (tombruijn) [inline spec/lib/appsignal/rack/sinatra_instrumentation_spec.rb]: Ignore, the `:mounted_at` option will be removed in #146

**Comment by thijsc** [comment]
👍

**Comment by matsimitsu** [comment]
👍
