### PR TITLE
Fix issue where errors without name could be sent

### LINKED ISSUE #186: Ignore invalid frontend errors (name is empty)
Check if error name is set, if not Ignore the payload and log an error.

### PR DESCRIPTION
**Pull request by matsimitsu**
The Rack middleware now returns a 422 code when exception name is not set.

Fixes #186

### CODE REVIEW

File: spec/lib/appsignal/js_exception_transaction_spec.rb [hunk 1]
```diff
@@ -78,6 +78,46 @@
...
+        transaction.set_action
+      end
+    end
+
+    describe "#set_metadata" do
+     it "should not call `Appsignal::Extension.set_transaction_metadata`" do
+       expect( transaction.ext ).to_not receive(:set_metadata)
+
+       transaction.set_metadata
+     end
```
Comment (tombruijn) [inline spec/lib/appsignal/js_exception_transaction_spec.rb]: Indenting is off, only 1 space instead of 2. Also for the specs below
Sorry, I spot these kinds of things

File: spec/lib/appsignal/rack/js_exception_catcher_spec.rb [hunk 2]
```diff
@@ -62,9 +69,42 @@
...
+      context "when `name` doesn't exist" do
+        let(:env) do
+          {
+            'PATH_INFO'  => '/appsignal_error_catcher',
+            'rack.input' => double(:read => '{"foo": ""}')
+          }
+        end
+
+        it "should not create a transaction" do
+          expect( Appsignal::JSExceptionTransaction ).to_not receive(:new)
```
Comment (tombruijn) [inline spec/lib/appsignal/rack/js_exception_catcher_spec.rb]: Inconsistent usage of spaces inside `expect()`

**Comment by tombruijn** [comment]
Rebased and fixed last inconsistent indenting

**Comment by tombruijn** [comment]
Rebased on `develop` and fixed conflicts with #175 #134

**Comment by matsimitsu** [comment]
+1
